[information]
name = 'github'
background = 'light'
author = 'Anthony Carapetis <anthony.carapetis@gmail.com>'
contributors = 'Lucas Tadeu <lucastadeuteixeira@gmail.com>,Wasin Pipattungsakul <wasin.pas@hotmail.com>'

[palette]
fg = '#000000'
bg = '#f6f8fa'

white = '#ffffff'
red = '#ff0000'

fold_fg = '#808080'
status_line_fg = '#404040'
diff_add_fg = '#003300'
diff_text_fg = '#000033'
diff_delete_fg = '#ddcccc'
win_bar_fg = '#888888'

cursor_bg = '#00f8f8'
search_bg = '#ffff8c'
float_bg = '#eaeef2'
fold_bg = '#ececec'
visual_bg = '#d4d4d4'
status_line_bg = '#bbbbbb'
error_bg = '#f8f8ff'
diff_add_bg = '#ddffdd'
diff_text_bg = '#ddddff'
diff_delete_bg = '#ffdddd'
lsp_reference_text_bg = '#d0d7de'
win_bar_bg = '#f6f8fa'

special_key = '#177f80'
white_space = '#e4e4e4'
line_number = '#959595'
match_paren = '#cdcdfd'

warning = '#ff895c'
error = '#ff0000'
info = '#888888'
hint = '#87d7ff'
ok = '#007000'

identifier = '#000000'
preprocessor = '#a0a0a0'
comment = '#999988'
constant = '#177f80'
string = '#990000'
function_ = '#005e9b'
type = '#6c19aa'
number = '#1c9898'
special = '#007000'
statement = '#d81745'

git_add = '#a0d3c1'
git_delete = '#e5886a'
git_change = '#cdcdfd'

spell_bad = '#fcaf3e'
spell_cap = '#73d216'
spell_local = '#729fcf'

status_line = '#f6f8fa'
record = '#ff0000'
n1 = '#000000'
n2 = '#404040'
i1 = '#005cc5'
i2 = '#00397a'
v1 = '#6f42c1'
v2 = '#442879'
c1 = '#008A63'
c2 = '#00563d'
r1 = '#d73a49'
r2 = '#8d1d27'
ro = '#ff0000'
status_line_remove = '#ef5939'

win_bar_modified = '#d7d787'
win_bar_git_dirty = '#d7afd7'
win_bar_indicator = '#5fafd7'
win_bar_icon = '#404040'

[highlights]
Normal = 'fg bg'
Cursor = 'bg cursor_bg'
Visual = '- visual_bg'
Search = 'fg search_bg b'
Folded = 'fold_fg fold_bg b'
Title = 'warning'
StatusLine = 'link:StatusLineN3'
StatusLineNC = 'status_line_fg visual_bg i'
SpecialKey = 'special_key - i'
WarningMsg = 'warning'
ErrorMsg = 'error error_bg c'
ColorColumn = '- white_space'
# SignColumn
VertSplit = 'status_line_bg bg'
LineNr = 'line_number bg'
LineNrAbove = 'git_add bg'
LineNrBelow = 'git_delete bg'
EndOfBuffer = 'bg'
Whitespace = 'white_space'
CursorLine = '- fold_bg'
CursorLineNr = 'function_ - b'
MatchParen = 'fg match_paren'
FoldColumn = 'link:Folded'
CursorColumn = 'link:CursorLine'
NonText = 'link:LineNr'
Directory = 'constant'

[floating-window]
Pmenu = 'fg float_bg'
PmenuSel = 'link:Visual'
PmenuSbar = 'line_number fold_bg'
PmenuThumb = 'status_line_bg status_line_bg'
PmenuBorder = 'float_bg float_bg'
PmenuPadding = 'float_bg bg'
PmenuTitle = 'fg float_bg b'
PmenuSeparator = 'visual_bg float_bg'
PmenuEnd = 'float_bg float_bg'

NormalFloat = '- bg'
FloatBorder = 'link:PmenuBorder'

[git]
DiffAdd = 'diff_add_fg diff_add_bg'
DiffChange = '- fold_bg'
DiffText = 'diff_text_fg diff_text_bg'
DiffDelete = 'diff_delete_fg diff_delete_bg'
GitSignsAdd = 'git_add'
GitSignsDelete = 'git_delete'
GitSignsChange = 'git_change'

[syntax]
Ignore = 'fold_fg'
Identifier = 'identifier'
PreProc = 'preprocessor - b'
Comment = 'comment'
Constant = 'constant'
String = 'string'
Function = 'function_'
Statement = 'statement'
Type = 'type'
Number = 'number'
Todo = 'white function_ b'
Special = 'special'
Label = 'fg - b'
StorageClass = 'link:Label'
Structure = 'link:Label'
TypeDef = 'link:Label'

'@variable' = 'link:Identifier'
'@variable.member' = 'type'
'@punctuation.delimiter' = 'special'
'@punctuation.bracket' = 'link:@punctuation.delimiter'
'@variable.builtin' = 'link:@punctuation.delimiter'
'@operator' = 'fg'
'@tag' = 'link:@function'
'@tag.attribute' = 'link:@variable.member'
'@tag.delimiter' = 'link:@punctuation.delimiter'

[lsp]
LspReferenceText = '- lsp_reference_text_bg'
LspReferenceRead = 'link:LspReferenceText'
LspReferenceWrite = 'link:LspReferenceText'
DiagnosticError = 'error'
DiagnosticWarn = 'warning'
DiagnosticInfo = 'info'
DiagnosticHint = 'hint'
DiagnosticOk = 'ok'

LspInfoBorder = 'link:PmenuPadding'

[nvim-navic]
NavicIconsModule = 'fg win_bar_bg b'
NavicIconsNamespace = 'identifier win_bar_bg'
NavicIconsPackage = 'link:NavicIconsModule'
NavicIconsClass = 'type win_bar_bg b'
NavicIconsMethod = 'function_ win_bar_bg b'
NavicIconsProperty = 'link:NavicIconsNamespace'
NavicIconsField = 'link:NavicIconsNamespace'
NavicIconsConstructor = 'special win_bar_bg b'
NavicIconsEnum = 'fg win_bar_bg b'
NavicIconsInterface = 'link:NavicIconsEnum'
NavicIconsFunction = 'link:NavicIconsMethod'
NavicIconsVariable = 'link:NavicIconsNamespace'
NavicIconsConstant = 'constant win_bar_bg'
NavicIconsString = 'string win_bar_bg'
NavicIconsNumber = 'number win_bar_bg'
NavicIconsArray = 'link:NavicIconsNamespace'
NavicIconsObject = 'link:NavicIconsNamespace'
NavicIconsStruct = 'link:NavicIconsClass'
NavicIconsBoolean = 'fg win_bar_bg'
NavicSeparator = 'status_line_bg win_bar_bg'

[spell]
SpellBad = '- - c spell_bad'
SpellCap = '- - c spell_cap'
SpellRare = 'link:SpellBad'
SpellLocal = '- - c spell_local'

[lines]
StatusLineN1 = 'status_line n1'
StatusLineN2 = 'status_line n2'
StatusLineRecord = 'record'
StatusLineN2Record = 'record n2'
StatusLineN3 = 'fg status_line'
StatusLineI1 = 'status_line i1'
StatusLineI2 = 'status_line i2'
StatusLineI2Record = 'record i2'
StatusLineI3 = 'i1 status_line'
StatusLineV1 = 'status_line v1'
StatusLineV2 = 'status_line v2'
StatusLineV2Record = 'record v2'
StatusLineV3 = 'v1 status_line'
StatusLineC1 = 'status_line c1'
StatusLineC2 = 'status_line c2'
StatusLineC2Record = 'record c2'
StatusLineC3 = 'c1 status_line'
StatusLineR1 = 'status_line r1'
StatusLineR2 = 'status_line r2'
StatusLineR2Record = 'record r2'
StatusLineR3 = 'r1 status_line'
StatusLineRO = 'red status_line'
StatusLineInactive = 'n2 visual_bg '
StatusLineError = 'error status_line'
StatusLineInfo = 'info status_line'
StatusLineHint = 'hint status_line'
StatusLineWarn = 'warning status_line'
StatusLineChanges = 'v1 status_line'
StatusLineGitAdded = 'ok status_line'
StatusLineGitRemoved = 'status_line_remove status_line'
StatusLineGitChanged = 'v1 status_line'

WinBar = 'win_bar_fg win_bar_bg'
WinBarNC = 'visual_bg'
WinBarLocation = 'link:WinBar'
WinBarModified = 'win_bar_modified win_bar_bg'
WinBarGitDirty = 'win_bar_git_dirty win_bar_bg'
WinBarIndicator = 'win_bar_indicator win_bar_bg'
WinBarIcon = 'win_bar_icon win_bar_bg'
WinBarIconDarker = 'win_bar_icon float_bg'

[noice]
NoiceCmdlinePopup = 'link:Pmenu'
NoiceCmdlinePopupBorder = 'link:PmenuPadding'
NoiceCmdlinePopupBorderSearch = 'link:NoiceCmdlinePopupBorder'
NoiceCmdlineIcon = 'link:Normal'
NoiceCmdlineIconLua = 'link:Function'
NoiceCmdlineIconFilter = 'link:Special'
NoiceCmdlineIconInput = 'type'
NoiceCmdlinePopupTitleInput = 'type float_bg b'
NoicePopup = 'link:Normal'
NoicePopupBorder = 'link:Normal'
NoicePopupmenuMatch = 'link:CmpItemAbbrMatch'
NoiceSplit = 'link:Normal'
NoiceConfirm = 'link:Pmenu'

[notify]
NotifyBackground = 'link:Pmenu'
NotifyERRORBody = '- bg'
NotifyWARNBody = 'link:NotifyERRORBody'
NotifyINFOBody = 'link:NotifyERRORBody'
NotifyDEBUGBody = 'link:NotifyERRORBody'
NotifyTRACEBody = 'link:NotifyERRORBody'
NotifyERRORIcon = 'link:DiagnosticError'
NotifyWARNIcon = 'link:DiagnosticWarn'
NotifyINFOIcon = 'link:DiagnosticInfo'
NotifyDEBUGIcon = 'link:DiagnosticHint'
NotifyERRORTitle = 'link:DiagnosticError'
NotifyWARNTitle = 'link:DiagnosticWarn'
NotifyINFOTitle = 'link:DiagnosticInfo'
NotifyDEBUGTitle = 'link:DiagnosticHint'

[telescope]
TelescopeNormal = 'fg float_bg'
TelescopePromptCounter = 'line_number'
TelescopePromptNormal = 'link:Pmenu'
TelescopeTitle = 'link:PmenuTitle'
TelescopeBorder = 'link:PmenuSeparator'
TelescopeResultsLineNr = 'line_number float_bg'

[cmp]
CmpItemAbbrDeprecated = 'fold_fg - s'
CmpItemAbbrMatch = 'function_ - b'
CmpItemAbbrMatchFuzzy = 'link:CmpItemAbbrMatch'
CmpItemKindVariable = 'link:Identifier'
CmpItemKindInterface = 'link:CmpItemKindVariable'
CmpItemKindText = 'link:CmpItemKindVariable'
CmpItemKindFunction = 'link:Function'
CmpItemKindMethod = 'link:CmpItemKindFunction'
CmpItemKindKeyword = 'link:Statement'
CmpItemKindProperty = 'link:CmpItemKindKeyword'
CmpItemKindUnit = 'link:CmpItemKindKeyword'

[blink-cmp]
BlinkCmpMenu = 'link:NormalFloat'
BlinkCmpLabelDeprecated = 'fold_fg - s'
BlinkCmpLabelMatch = 'function_ - b'
BlinkCmpKind = 'link:Normal'
BlinkCmpKindVariable = 'link:Identifier'
BlinkCmpKindInterface = 'link:BlinkCmpKindVariable'
BlinkCmpKindText = 'link:BlinkCmpKindVariable'
BlinkCmpKindFunction = 'link:Function'
BlinkCmpKindMethod = 'link:BlinkCmpKindFunction'
BlinkCmpKindModule = 'fg'
BlinkCmpKindKeyword = 'link:Statement'
BlinkCmpKindProperty = 'link:BlinkCmpKindKeyword'
BlinkCmpKindEnum = 'link:Type'
BlinkCmpKindEnumMember = 'link:BlinkCmpKindKeyword'
BlinkCmpKindField = 'link:BlinkCmpKindKeyword'
BlinkCmpKindUnit = 'link:BlinkCmpKindKeyword'
BlinkCmpKindSnippet = 'link:Special'
BlinkCmpKindClass = 'link:Type'
BlinkCmpKindStruct = 'link:BlinkCmpKindClass'
BlinkCmpKindConstant = 'link:Constant'
BlinkCmpKindValue = 'link:BlinkCmpKindConstant'
BlinkCmpKindFile = 'link:BlinkCmpKindModule'
BlinkCmpKindFolder = 'link:Number'

# BlinkCmpKindText xxx links to BlinkCmpKind
# BlinkCmpKindMethod xxx links to BlinkCmpKind
# BlinkCmpKindFunction xxx links to BlinkCmpKind
# BlinkCmpKindConstructor xxx links to BlinkCmpKind
# BlinkCmpKindField xxx links to BlinkCmpKind
# BlinkCmpKindVariable xxx links to BlinkCmpKind
# BlinkCmpKindClass xxx links to BlinkCmpKind
# BlinkCmpKindInterface xxx links to BlinkCmpKind
# BlinkCmpKindModule xxx links to BlinkCmpKind
# BlinkCmpKindProperty xxx links to BlinkCmpKind
# BlinkCmpKindUnit xxx links to BlinkCmpKind
# BlinkCmpKindValue xxx links to BlinkCmpKind
# BlinkCmpKindEnum xxx links to BlinkCmpKind
# BlinkCmpKindKeyword xxx links to BlinkCmpKind
# BlinkCmpKindColor xxx links to BlinkCmpKind
# BlinkCmpKindFile xxx links to BlinkCmpKind
# BlinkCmpKindReference xxx links to BlinkCmpKind
# BlinkCmpKindFolder xxx links to BlinkCmpKind
# BlinkCmpKindEnumMember xxx links to BlinkCmpKind
# BlinkCmpKindConstant xxx links to BlinkCmpKind
# BlinkCmpKindStruct xxx links to BlinkCmpKind
# BlinkCmpKindEvent xxx links to BlinkCmpKind
# BlinkCmpKindOperator xxx links to BlinkCmpKind
# BlinkCmpKindTypeParameter xxx links to BlinkCmpKind

[nvim-tree]
NvimTreeNormal = 'link:Pmenu'
NvimTreeNormalFloat = 'link:Pmenu'
NvimTreeLineNr = 'link:Pmenu'
NvimTreeCursorLine = 'link:PmenuSel'
NvimTreeEndOfBuffer = 'link:PmenuBorder'

[neo-tree]
NeoTreeRootName = 'constant - b'
NeoTreeTitleBar = 'link:TelescopeTitle'
NeoTreeNormal = 'link:Pmenu'
NeoTreeFloatNormal = 'link:Pmenu'
NeoTreeFloatTitle = 'link:NeoTreeFloatBorder'
NeoTreeLineNr = 'link:Pmenu'
NeoTreeCursorLine = 'link:PmenuSel'
NeoTreeEndOfBuffer = 'link:PmenuBorder'
NeoTreeGitAdded = 'ok'
NeoTreeGitDeleted = 'status_line_remove'
NeoTreeGitModified = 'v1'
NeoTreeGitUntracked = 'warning'
NeoTreeGitConflict = 'warning - b'

[file-type]
yamlBool = 'link:Special'
yamlNull = 'link:Special'
yamlPlainScalar = 'link:String'
yamlFlowCollection = 'link:@punctuation.delimiter'
yamlBlockCollectionItemStart = 'link:@punctuation.delimiter'

[misc]
LazyNormal = 'link:Pmenu'

WhichKeyFloat = 'link:Pmenu'

DashboardHeader = 'link:Ignore'
DashboardText = 'function_'
DashboardFooter = 'link:Comment'
DashboardDesc = 'link:Function'
DashboardIcon = 'link:DashboardDesc'
DashboardKey = 'link:String'


MasonNormal = 'link:Pmenu'
MasonHeader = 'link:PmenuTitle'

FlashLabel = 'white function_ b'
FlashPromptIcon = 'search_bg warning'

Floaterm = 'link:Pmenu'
FloatermBorder = 'link:Pmenu'
